### ISSUE TITLE
Single-post images not pulling and videos are lower quality and open two tabs

### ISSUE THREAD

**Issue by runchbox** [theus/instantgram#62]
Hi, 4.0.7 with Firefox 97.0.1.
Videos open two tabs, sometimes the same video, sometimes two videos, and they are all of lower quality than normal.

Single image posts mostly do not open however multi-image posts all seem to work well.

Thank you for everything.

**Comment by theus** [comment]
@runchbox thanks for the issue

**Comment by slomomojo** [comment]
_(v = video, p = image)_

Hello,

The video bug seems straightforward.  It opens an extra tab one video behind:
https://www.instagram.com/p/CcYAQmnuuEY/

1v, 2v, 3v

1v -> 1v 1v
2v -> 2v 1v
3v -> 3v 2v

When video is mixed with images it can prevent the images from opening:
https://www.instagram.com/p/CXcBUbNhNef/

1p, 2v, 3p, 4p, 5v, 6p

1p -> 2v
2v -> 2v 2v
3p -> 2v
4p -> 5v
5v -> 5v 5v
6p -> 5v

This is on Arch Linux with Firefox, adblockers disabled.

**Comment by theus** [comment]
The new version should be working https://theus.github.io/instantgram/

**Comment by slomomojo** [comment]
Hi,

I'm still having problems so I'm not sure this is the same issue as the recent changes.

1) https://www.instagram.com/p/CcYAQmnuuEY/
In this example of 3 videos in the regular, non-story post the first opens correctly, the second does not open, and the third opens a still frame from the video.

2) https://www.instagram.com/p/CXcBUbNhNef/ 
This example still only shows video and no images as per my previous post.

It looks like a video is opening one behind and one ahead if mixed with images.  If there are two images after the video and no following video, the second image will open.

Again,  this is Firefox on Linux.  Maybe someone else can confirm if they are seeing the same results?

**Comment by onmyouji** [comment]
> 
>     1. https://www.instagram.com/p/CcYAQmnuuEY/
>        In this example of 3 videos in the regular, non-story post the first opens correctly, the second does not open, and the third opens a still frame from the video.
> 
>     2. https://www.instagram.com/p/CXcBUbNhNef/
>        This example still only shows video and no images as per my previous post.
> 
> 

Same here, I tested your links and have the same issue. I'm running Firefox on Windows.
